image: "node:14"
pipelines:
  default:
  - step:
      name: "Install"
      caches:
        - node
      script:
        - "npm install"
        - "npm run lint"
        - "npm run test"
        - "npm run build"