name: AWS Deploy - Next
on:
  push:
    branches:
      - feature/*
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_STUDIO_PRD_BUCKET_REGION }}
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/ s3://studio.radical.tools.next --delete --cache-control max-age=31536000,public
      - name: Set proper cache for index.html
        run: aws s3 cp s3://studio.radical.tools.next/studio/index.html s3:/studio.radical.tools.next/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
