name: Commit Validation
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/cache@v2
      #   with:
      #     path: "**/node_modules"
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run lint
      - run: npm run prettier
      - run: npm run test
      - run: npm run build
      - run: npm install serve -g
      - run: (serve -s build&)
      - run: npm run test-e2e
